### PR TITLE
fix rust logo

### PR DESCRIPTION
**Pull request by queenkoopa8500**

### CODE REVIEW

**Comment by queenkoopa8500** [comment]
to see how it looks you can view the README here https://github.com/uuphoria2/Tarnadas

**Comment by Tarnadas** [comment]
Thx!

**Comment by queenkoopa8500** [comment]
> Thx!

np!

**Comment by uuphoria2** [comment]
> Thx!

yo i just wanna say tarnadas, how could i get a sm64js remake since im trying to make on namecheap shared hosting i just wanna ask should i use server files or docker too (deployed site)? if i just use server files then should i put it in the main domain or put it in the server subdomain im new to this stuff and could really use some help
Cheers, uuphoria

**Comment by uuphoria2** [comment]
btw i have big plans for this like more features or characters im not sure where im gonna start yet.

**Comment by uuphoria2** [comment]
@Tarnadas sorry for making so many replies tho lastly what i wanna say about this is that im using the rust servers you developed so i need some advice from you to get this running
thats all i wanted to ask for web development and sm64js remakes and server stuff

**Comment by uuphoria2** [comment]
@Tarnadas Review my new pull request please #3

**Pull request merged**
